apiVersion: v1
kind: Pod
metadata:
  name: xyz
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - tail -f /dev/null
      image: mysql:5.7
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      name: mysql
  restartPolicy: Always