apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: sq-packet-test
spec:
  version: latest
  timezone: UTC
  enableTLSCluster: false
  pvReclaimPolicy: Delete
  enableAdvertiseAddress: true
  autoFailover: false
  configUpdateStrategy: RollingUpdate
  pd:
    baseImage: pingcap/pd
    version: v4.0.8
    replicas: 1
    service:
      type: NodePort
    storageClassName: shared-nvme-disks
    tlsClientSecretName: sq-packet-test-pd-dashboard-client-secret
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 8Gi
      storage: 200Gi
    config:
      log-level: "info"
      location-labels: "test"

  tikv:
    baseImage: pingcap/tikv
    version: v4.0.8
    replicas: 3
    storageClassName: shared-nvme-disks
    maxFailoverCount: 0
    limits:
      cpu: 8000m
      memory: 24Gi
      storage: 3000Gi
    requests:
      cpu: 2000m
      memory: 16Gi
      storage: 3000Gi
    config:
      log-level: "info"
      status-addr: "0.0.0.0:20180"
      storage:
        block-cache:
          capacity: "14GB"
          shared: true
      raftstore:
        pd-heartbeat-tick-interval: "60s"
        raft-max-inflight-msgs: 8912
        perf-level: 5
        hibernate-regions: false

  tidb:
    baseImage: pingcap/tidb
    version: v4.0.8
    replicas: 1
    maxFailoverCount: 0
    enableAdvertiseAddress: true
    tlsClient:
      enabled: true
    service:
      type: ClusterIP
    config:
      new_collations_enabled_on_first_bootstrap: true
      token-limit: 1000000
      log-level: "info"
      prepared_plan_cache:
        enabled: true
      security:
        require-secure-transport: true
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 8Gi
---
apiVersion: pingcap.com/v1alpha1
kind: TidbInitializer
metadata:
  name: sq-packet-test-init
  namespace: sq
spec:
  image: tnir/mysqlclient
  cluster:
    namespace: sq
    name: sq-packet-test
  initSql: |-
    create database app;
  tlsClientSecretName: sq-packet-test-tidb-initializer-client-secret