apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-run
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    spec:
      containers:
        - name: prepare-run-test
          image: lysu/demo:latest
          command:
            - /bin/sh
            - -c
            - |-
              set -x
              keytool -noprompt -importcert -alias tidbCA -file /var/lib/tidb-client-tls/ca.crt -keystore truststore -storepass 123456
              openssl pkcs12 -export -in /var/lib/tidb-client-tls/tls.crt -inkey /var/lib/tidb-client-tls/tls.key -name "testclient" -passout pass:123456 -out client-keystore.p12
              keytool -noprompt -importkeystore -srckeystore client-keystore.p12 -srcstoretype pkcs12 -srcstorepass 123456 -destkeystore keystore -deststoretype JKS -deststorepass 123456
              java -Djavax.net.ssl.trustStore=/truststore -Djavax.net.ssl.trustStorePassword=123456 -Djavax.net.ssl.keyStore=/keystore -Djavax.net.ssl.keyStorePassword=123456 -jar demo-0.0.1-SNAPSHOT.jar
          env:
            - name: TIDB_HOST
              value: "${ENV_TIDB_HOST}"
          volumeMounts:
            - mountPath: /var/lib/tidb-client-tls
              name: tidb-client-tls
              readOnly: true
      volumes:
        - name: tidb-client-tls
          secret:
            defaultMode: 420
            secretName: sq-packet-test-tidb-client-secret
      restartPolicy: Never