apiVersion: batch/v1
kind: Job
metadata:
  name: tpcc-prepare-5k
  labels:
    app: tpcc
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    metadata:
      labels:
        app: tpcc
    spec:
      nodeSelector:
        pool: benchmark
      tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: benchmark
      containers:
        - name: tpcc
          image: aylei/go-tpc:20201027
          command:
            - /bin/sh
            - -c
            - |-
              set -x
              set -euo pipefail
              elapseTime=0
              threshold=600
              while true; do
                  sleep 5
                  elapseTime=$(( elapseTime+5 ))

                  if [[ ${elapseTime} -ge ${threshold} ]]
                  then
                      echo "waiting for TiDB endpoint ready timeout" >&2
                      exit 1
                  fi

                  if nslookup ${TIDB_HOST} 2>/dev/null
                  then
                      echo "nslookup domain ${TIDB_HOST} success"
                      break
                  else
                      echo "nslookup domain ${TIDB_HOST} failed" >&2
                  fi
              done
              mysql -h${TIDB_HOST} -P${TIDB_PORT} -p${PASSWORD} -e "DROP DATABASE IF EXISTS tpcc; CREATE DATABASE tpcc;"
              /go-tpc -H=${TIDB_HOST} -P=${TIDB_PORT} -p=${PASSWORD} -D=tpcc --warehouses=${WAREHOUSES} tpcc prepare
          env:
            - name: TIDB_HOST
              value: "${ENV_TIDB_HOST}"
            - name: TIDB_PORT
              value: "${ENV_TIDB_PORT}"
            - name: PASSWORD
              value: "${ENV_PASSWORD}"
            - name: WAREHOUSES
              value: "5000"
            - name: DURATION
              value: "120m"
            - name: TERMINALS
              value: "100"
      restartPolicy: Never