apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: robitest
spec:
  version: latest
  timezone: UTC
  enableTLSCluster: false
  pvReclaimPolicy: Delete
  enableAdvertiseAddress: true
  autoFailover: false
  configUpdateStrategy: RollingUpdate 
  pd:
    baseImage: hub.pingcap.net/pingcap/pd
    version: ef58212
    replicas: 1
    service:
      type: NodePort
    storageClassName: shared-nvme-disks
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 8Gi
      storage: 200Gi
    config:
      log-level: "info"
      location-labels: "test"

  tikv:
    baseImage: hub.pingcap.net/pingcap/tikv
    version: ca88a46
    replicas: 3
    storageClassName: shared-nvme-disks
    maxFailoverCount: 0
    limits:
      cpu: 8000m
      memory: 24Gi
      storage: 3000Gi
    requests:
      cpu: 2000m
      memory: 16Gi
      storage: 3000Gi
    config:
      log-level: "info"
      status-addr: "0.0.0.0:20180"
      storage:
        block-cache:
          capacity: "14GB"
          shared: true
      raftstore:
        pd-heartbeat-tick-interval: "60s"
        raft-max-inflight-msgs: 8912
        perf-level: 5
        hibernate-regions: false

  tidb:
    baseImage: hub.pingcap.net/pingcap/tidb
    version: 280e8aa
    replicas: 1
    maxFailoverCount: 0
    enableAdvertiseAddress: true
    service:
      type: ClusterIP
    config:
      new_collations_enabled_on_first_bootstrap: true
      token-limit: 1000000
      log-level: "info"
      prepared_plan_cache:
        enabled: true
      experimental:
        allow-auto-random: true
    limits:
      cpu: 4000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 8Gi

